# Generated by Django 4.2.6 on 2023-10-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='funding_program',
        ),
    ]
